development:
  adapter: mysql2
  database: thelare
  username: root
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: thelare-test
  username: root
  password: 
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: thelare
  username: root
  password: 
  pool: 5
  timeout: 5000